<?php

namespace Magium\WebDriver;

use Facebook\WebDriver\Remote\RemoteExecuteMethod;
use Magium\Util\Log\Logger;

class LoggingRemoteExecuteMethod extends RemoteExecuteMethod
{
    protected $logger;

    public function __construct(WebDriver $driver, Logger $logger)
    {
        parent::__construct($driver);
        $this->logger = $logger;
    }


    public function execute(
        $command_name,
        array $parameters = array()
    )
    {
        $extra = [
            'type'      => 'webdriver-activity',
            'activity'  => 'action',
            'command'   => $command_name
        ];

        if (isset($parameters[':id'])) {
            $extra['id'] = $parameters[':id'];
        }

        $this->logger->debug(
            sprintf(
                'Executing: ' . $command_name
            ),
            $extra
        );
        return parent::execute($command_name, $parameters); // TODO: Change the autogenerated stub
    }


}